[package]
name = "router_attr_wrapper"
version = "0.1.0"
authors = ["k.bagrov <k.bagrov@g.nsu.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
router_attr = { path = "../router_attr" }
rouille = "3.0.0"